# version: "3.9"

# services:
#   backend:
#     build: ./be
#     container_name: pushapp_backend
#     command: daphne -b 0.0.0.0 -p 8000 config.asgi:application # ✅ 이 줄만 수정!
#     env_file:
#       - ./be/.env
#     expose:
#       - "8000"
#     depends_on:
#       - db_user
#     networks:
#       - kioedu_network

#   frontend:
#     build:
#       context: ./app
#       dockerfile: Dockerfile
#     working_dir: /app
#     volumes:
#       - ./app:/app
#       - /app/node_modules
#     depends_on:
#       - backend
#     command: ["npm", "run", "build"]
#     networks:
#       - kioedu_network

#   nginx:
#     image: nginx:stable-alpine
#     container_name: pushapp_nginx
#     ports:
#       - "8080:80"
#       - "8443:443"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./app/dist:/usr/share/nginx/html
#       - static_volume:/app/static
#       - media_volume:/app/media
#     depends_on:
#       - backend
#     networks:
#       - kioedu_network

#   db_user:
#     image: postgres:16
#     container_name: pushapp_db
#     restart: always
#     environment:
#       POSTGRES_DB: kioedu
#       POSTGRES_USER: rheavision
#       POSTGRES_PASSWORD: 16444907
#     volumes:
#       - pgdata_user:/var/lib/postgresql/data
#     ports:
#       - "5435:5432"
#     networks:
#       - kioedu_network

# networks:
#   kioedu_network:
#     external: true
#     name: kioedu_network

# volumes:
#   static_volume:
#   media_volume:
#   pgdata_user:

version: "3.9"

services:
  backend:
    build: ./be
    container_name: pushapp_backend
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file:
      - ./be/.env
    expose:
      - "8000"
    depends_on:
      - db_user
    volumes:
      - media_volume:/app/media # ⭐ 추가!
      - static_volume:/app/staticfiles
    networks:
      - kioedu_network

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules

    depends_on:
      - backend
    command: ["npm", "run", "build"]
    networks:
      - kioedu_network

  nginx:
    image: nginx:stable-alpine
    container_name: pushapp_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist:/usr/share/nginx/html
      - static_volume:/app/staticfiles
      - media_volume:/app/media # ⭐ nginx도 같은 볼륨 사용
    depends_on:
      - backend
    networks:
      - kioedu_network

  db_user:
    image: postgres:16
    container_name: pushapp_db
    restart: always
    environment:
      POSTGRES_DB: kioedu
      POSTGRES_USER: rheavision
      POSTGRES_PASSWORD: 16444907
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - kioedu_network

networks:
  kioedu_network:
    external: true
    name: kioedu_network

volumes:
  static_volume:
  media_volume:
  pgdata_user:
